### ISSUE TITLE
Possible debounce race causes actions to be dropped

### ISSUE THREAD

**Issue by arronmabrey** [michaelcontento/redux-storage-decorator-debounce#29]
Hello @michaelcontento,

As described in the title, I believe there may be a possible race condition that's causing actions to be dropped. 

I'm using this library in a react-native project to persist redux state to the device after a configured debounce time.
### Scenario

> Given a button press that dispatches a redux action approximately about the same time the debounce window closes and writes redux state to disk. I have observed the button press action is dropped as though it never happened.

I do want to caveat that at this point I'm not 100% sure what's at fault, but based on observations, I believe something along the following may be happening.
1. debounce window opens
2. ... redux actions keep the window open ...
3. idle time approaching debounce window close
4. debounce window begins closing
5. debounce captures current state to write to disk
6. user presses button and dispatches last action
7. debounce finishes writing state without last user action
8. returns new state without last user action

If indeed the above sequence is actually happening, any actions between step 5 and step 7 would be dropped.

Thanks for you time

**Comment by michaelcontento** [comment]
Sorry for the late response.
And sorry to bring the sad news to you, but my focus has left the node / react ecosystem and this package is no longer maintained 😞

**Comment by michaelcontento** [comment]
Re-opened as @guns2410 want's to work on this project: Give him a warm welcome 👏

**Comment by guns2410** [comment]
Thanks @michaelcontento 

@arronmabrey do you see any error messages in the console if you use redux logger. Also, does this occur if you do not debounce?

**Comment by arronmabrey** [comment]
I was using redux dev tools as well as redux logger. I did not see any console warnings when I was observing this. I will say it's really tricky to reproduce because of the timing involved.

**Comment by guns2410** [comment]
Ok, I am closing this for now, but feel free to reopen in case you see it again.
